### ISSUE TITLE
Null Error

### ISSUE THREAD

**Issue by ALI3D69** [DrOffensive/PlayerPrefsUtility#1]
it says this is null in line 76:
Registry.CurrentUser.OpenSubKey(registyPath)
and Line 58.

**Comment by DrOffensive** [comment]
I will check it out. But it might take a few days due to the holidays.
I'll let you know when I've investigated the issue.

søn. 24. dec. 2023 10.45 skrev ALI3D69 ***@***.***>:

**Comment by DrOffensive** [comment]
I have committed a possible fix for your issue, it should be live within
the next couple of days.
Please let me know if it solves it for you.
Happy new year.
Regards MarcWerk

Den søn. 24. dec. 2023 kl. 10.45 skrev ALI3D69 ***@***.***>:
